name: std
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3
  - pip
  - python=3.9
  - pytorch=1.12.1
  - torchvision=0.13.1
  - pip:
    - black==21.7b0
    - click==8.0.4
    - deepdiff==6.3.0
    - datasets==2.11.0
    - einops==0.6.0
    - fire
    - flake8==3.9.2
    - isort==5.9.2
    - neptune==1.2.0
    - notebook
    - timm==0.6.13
    - torchinfo==1.7.0