game_name: "Frostbite" # MsPacman, Frostbite, Gravitar, Hero, MontezumaRevenge, Phoenix, StarGunner

# Mode switching parameters
exploration_type: "XU-100-informed-fixed-X"
explore_duration: 100
exploit_duration: 1000
prob_switch_exploit: 0
start_mode: "X"

# Value promise / Homeostasis parameters
informed_k: 5
target_rate: 0.01

# Training / optimizer parameters
lr: 1.0e-4
eps: 1.0e-3
grad_norm: 40
batch_size: 64
learning_starts: 50000
save_interval: 500
target_net_update_interval: 2000
gamma: 0.997
prio_exponent: 0.9
importance_sampling_exponent: 0.6
training_steps: 100000
buffer_capacity: 2000000
max_episode_steps: 27000
actor_update_interval: 400
block_length: 400

# Agent parameters
num_actors: 8
base_eps: 0.4
alpha: 7
log_interval: 10

# Sequence parameters
burn_in_steps: 40
learning_steps: 40
forward_steps: 5

# Model parameters
hidden_dim: 512

# Testing parameters
render: True
save_plot: True
test_epsilon: 0.001
